import { dirname as Dir, resolve as Resolve } from "path";
import Piscina from "piscina";
import { fileURLToPath as Path } from "url";
const NameFile = Path(import.meta.url);

const Calculation = new Piscina({
	filename: Resolve(`${Dir(NameFile)}/../../dist/test/calculation.js`),
	concurrentTasksPerWorker: 10.0,
});

const Fn = new Piscina({
	filename: Resolve(`${Dir(NameFile)}/../../dist/test/function-call.js`),
	concurrentTasksPerWorker: 10.0,
});

await Promise.all([
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
	Calculation.run({}),
	Fn.run({}),
]);
